name: Node.js CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            # Navigate to the project directory
            cd /var/www/html/softypy-server
            
            # Pull the latest changes from the main branch
            git pull origin main
            
            # Install/update dependencies
            npm install
            
            
            # Check if the PM2 process is already running and manage accordingly
            if pm2 describe softypy-server > /dev/null; then
              echo "Restarting softypy-server..."
              pm2 restart softypy-server
            else
              echo "Starting softypy-server..."
              pm2 start npm --name "softypy-server" -- run start
            fi
            
            # Save the PM2 process list to ensure it restarts on system reboot
            pm2 save
            
